---
title: "day7_String"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(stringr)
library(janitor)
```

```{r}
my_string <- c("burrito", "fish taco", "taco salad")

my_string %>% 
  str_detect(my_string)
```

```{r}
skywalkers <- starwars %>%
  filter(str_detect(name, pattern = "Skywalker"))

mauls <- starwars %>%
  filter(str_detect(name, pattern = "Maul"))

#create a subset that keeps rows where "blue" shows up in the eye color either alone or in combinatiom

blue_eyes <- starwars %>%
  filter(str_detect(eye_color, pattern = "blue"))

```

str_replace to replace string patters

```{r}
firewalkers <- starwars %>%
  mutate(name_2 = str_replace(name, pattern = "Sky", replacement = "Fire"))
```

```{r}
feedback <- c("   I ate     some    nachos", "Wednesday      morning  ")


str_trim(feedback)
str_squish(feedback)

#str_to
str_to_lower(feedback)
str_to_upper(feedback)
str_to_title(feedback)
str_to_sentence(feedback)



starwars_lc <- starwars %>%
  mutate(name_lower = str(str_to_lower(name)))
```

## Case_when()

```{r}
sw_robot <- starwars %>%
  mutate(robot_status = case_when(
    species == "Droid" ~ "A ROBOT!!!",
    species == "Human" ~ "It's a human",
    TRUE ~ "so,ething"
  ))
```
