---
title: "Day 7 Notes"
author: "Andre Dextre"
date: "2022-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(lubridate)
library(kableExtra)
```

## Part 1: Data Wrangling Refresher

```{r}
pen_ex <- penguins %>%
  group_by(island) %>%
  filter(island == "Biscoe"|
         island == "Dream")
  
```








```{r}
teddy_bday <- lubridate::ymd("20170615")

wday(teddy_bday, label = TRUE)

mybday <- lubridate::ymd(("19980429"))

wday(mybday, label = TRUE)

```

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purpple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_ymd <- urchin_counts %>%
  mutate(date = mdy(date)) %>%
  mutate(year = year(date),
         month = month(date),
         day = day(date))

```

```{r}
day_1 <- ymd("2020-01-06")
day_2 <- ymd("2020-05-18")

time_interval <- interval(day_1, day_2)

time_length(time_interval, "year")
```

```{r}

```

